// Generated by scripts/generate-strapi-schema.mjs — do not edit by hand.
// Re-run `pnpm run strapi:schema` after changing Strapi content types.
import { z } from "astro/zod";

const mediaSchema = z
  .object({
    name: z.string(),
    alternativeText: z.string().nullable().optional(),
    caption: z.string().nullable().optional(),
    width: z.number().nullable().optional(),
    height: z.number().nullable().optional(),
    formats: z
      .record(
        z.string(),
        z
          .object({
            url: z.string(),
            width: z.number(),
            height: z.number(),
          })
          .passthrough(),
      )
      .nullable()
      .optional(),
    hash: z.string(),
    ext: z.string().optional(),
    mime: z.string(),
    size: z.number(),
    url: z.string(),
    previewUrl: z.string().nullable().optional(),
    provider: z.string(),
    createdAt: z.string(),
    updatedAt: z.string(),
  })
  .passthrough();

/** One node of a Strapi rich-text (blocks) field. */
const blockSchema = z
  .object({
    type: z.string(),
    level: z.number().optional(),
    children: z
      .array(z.object({ type: z.string().optional(), text: z.string().optional() }).passthrough())
      .optional(),
  })
  .passthrough();

export const practiceAreasSchema = z
  .object({
    id: z.number().optional(),
    documentId: z.string().optional(),
    createdAt: z.string().optional(),
    updatedAt: z.string().optional(),
    publishedAt: z.string().nullable().optional(),
    value: z.string().nullable().optional(),
    teachers: z
      .array(
        z
          .object({
            name: z.string().nullable().optional(),
            title: z.string().nullable().optional(),
            quote: z.string().nullable().optional(),
            credentials: z
              .array(
                z
                  .object({
                    label: z.string().nullable().optional(),
                    primary: z.string().nullable().optional(),
                    secondary: z.string().nullable().optional(),
                  })
                  .passthrough(),
              )
              .nullable()
              .optional(),
            portrait: mediaSchema.nullable().optional(),
            practice_areas: z
              .object({ id: z.number().optional(), documentId: z.string().optional() })
              .passthrough()
              .nullable()
              .optional(),
            education: z
              .array(
                z
                  .object({
                    school: z.string().nullable().optional(),
                    degree: z.string().nullable().optional(),
                  })
                  .passthrough(),
              )
              .nullable()
              .optional(),
            bar_admission: z
              .array(
                z
                  .object({
                    jurisdiction: z.string().nullable().optional(),
                    year: z.string().nullable().optional(),
                  })
                  .passthrough(),
              )
              .nullable()
              .optional(),
            highlight: z
              .object({
                label: z.string().nullable().optional(),
                title: z.string().nullable().optional(),
                description: z.string().nullable().optional(),
              })
              .passthrough()
              .nullable()
              .optional(),
            stat: z
              .array(
                z
                  .object({
                    value: z.string().nullable().optional(),
                    description: z.array(blockSchema).nullable().optional(),
                  })
                  .passthrough(),
              )
              .nullable()
              .optional(),
            contact: z
              .object({
                intro: z.string().nullable().optional(),
                phone: z.string().nullable().optional(),
                email: z.string().email().nullable().optional(),
                address: z.string().nullable().optional(),
              })
              .passthrough()
              .nullable()
              .optional(),
            philosophy_quote: z.string().nullable().optional(),
            philosophy_attribution: z.string().nullable().optional(),
            Bio: z.array(blockSchema).nullable().optional(),
          })
          .passthrough(),
      )
      .nullable()
      .optional(),
  })
  .passthrough();

export const teachersSchema = z
  .object({
    id: z.number().optional(),
    documentId: z.string().optional(),
    createdAt: z.string().optional(),
    updatedAt: z.string().optional(),
    publishedAt: z.string().nullable().optional(),
    name: z.string().nullable().optional(),
    title: z.string().nullable().optional(),
    quote: z.string().nullable().optional(),
    credentials: z
      .array(
        z
          .object({
            label: z.string().nullable().optional(),
            primary: z.string().nullable().optional(),
            secondary: z.string().nullable().optional(),
          })
          .passthrough(),
      )
      .nullable()
      .optional(),
    portrait: mediaSchema.nullable().optional(),
    practice_areas: z
      .array(
        z
          .object({
            value: z.string().nullable().optional(),
            teachers: z
              .object({ id: z.number().optional(), documentId: z.string().optional() })
              .passthrough()
              .nullable()
              .optional(),
          })
          .passthrough(),
      )
      .nullable()
      .optional(),
    education: z
      .array(
        z
          .object({
            school: z.string().nullable().optional(),
            degree: z.string().nullable().optional(),
          })
          .passthrough(),
      )
      .nullable()
      .optional(),
    bar_admission: z
      .array(
        z
          .object({
            jurisdiction: z.string().nullable().optional(),
            year: z.string().nullable().optional(),
          })
          .passthrough(),
      )
      .nullable()
      .optional(),
    highlight: z
      .object({
        label: z.string().nullable().optional(),
        title: z.string().nullable().optional(),
        description: z.string().nullable().optional(),
      })
      .passthrough()
      .nullable()
      .optional(),
    stat: z
      .array(
        z
          .object({
            value: z.string().nullable().optional(),
            description: z.array(blockSchema).nullable().optional(),
          })
          .passthrough(),
      )
      .nullable()
      .optional(),
    contact: z
      .object({
        intro: z.string().nullable().optional(),
        phone: z.string().nullable().optional(),
        email: z.string().email().nullable().optional(),
        address: z.string().nullable().optional(),
      })
      .passthrough()
      .nullable()
      .optional(),
    philosophy_quote: z.string().nullable().optional(),
    philosophy_attribution: z.string().nullable().optional(),
    Bio: z.array(blockSchema).nullable().optional(),
  })
  .passthrough();

export const testSchema = z
  .object({
    id: z.number().optional(),
    documentId: z.string().optional(),
    createdAt: z.string().optional(),
    updatedAt: z.string().optional(),
    publishedAt: z.string().nullable().optional(),
  })
  .passthrough();
